hw4
PoLoSkA/MyNews pull request #4
Opened 2018-10-30 20:44 UTC by PoLoSkA

hw4

2018-11-03 07:46 UTC, PStrelchenko requested changes
Реквестирую больше кода богу кода!

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/NewsDetailsActivity.java
> +        final NewsDisplayableModel news = (NewsDisplayableModel) getIntent().getSerializableExtra(NEWS_KEY_EXTRA);
Что способ с JSON, что способ через serializable - не очень гут, но ты об этом и так знаешь =)
Этот коммент про то, что "не оставляй закомментированный код в проде" --> не очень хорошая практика. Такой мертвый код остается, как правило, надолго

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/NewsDetailsActivity.java
> +    public static void start(@NonNull Context context, @NonNull NewsDisplayableModel item){
Помним про то, что не надо перемешивать методы статические и нестатические - вынеси куда-нибудь наверх, к статическим полям

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        progressBar.setVisibility(ProgressBar.INVISIBLE);
А почему `INVISIBLE`? Этот режим же просто скрывает View, а не убирает его, и у тебя могут возникнуть странные отступы при показе чего-либо.

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        if (disposable != null && !disposable.isDisposed()) {
Получается, что у тебя запрос умирает как только ты сворачиваешь приложение. (onStop -> и ты освобождаешь disposable). 
Это не очень круто.

Давай мы доработаем приложение так, чтобы запрос сохранялся при переворотах экрана, при сворачивании приложения и тд.
Можешь использовать любой из способов: Loaders, Moxy, ViewModel (лучше последние два +))

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +                subscribe(this::updateItems);
Если произойдет какая-то ошибка в конвертере, или generateNews --> у тебя приложение крашнется, потому что ты не сделал обработчик ошибки в subscribe.
Добавь обработку ошибки - сделай error stub с текстом ошибки и кнопкой Retry, которая попробует подгрузить новости еще раз + show snackbar

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        progressBar.setVisibility(ProgressBar.INVISIBLE);
Почему `INVISIBLE`, а не `GONE`?

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/data/DataUtils.java
> +        try {
Эту же штуку можно перенести в твою Rx цепочку - там есть оператор delay

-->
```
Single.fromCallable { ... }
   .delay(5, TimeUnit.SECONDS) // или delay(5000, TimeUnit.MILLISECONDS)
```

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews).
`Observable` здесь не нужен, замени на `Single` --> ты хочешь сделать emit лишь 1 элемента - одного списка. А `Observable` предназначен для эмитинга от 0 до N элементов.

Просто замени `Observable` на `Single`

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +                subscribeOn(Schedulers.io()).
Потратил пару лишних секунд, чтобы разобраться, на каком потоке выполнится `map` =)
Я бы на твоем месте перенес `subscribeOn` на строчку ниже, чтобы этот оператор был ниже `map`.
`SubscribeOn` (в самом простом приближении) планирует выполнение всех операторов, которые находятся выше от него на указанном потоке. И действует это до следующего observeOn.

Такие дела. 

Итого - мне кажется, что 

```
Single.fromCallable { ... }
    .map( ... )
    .subscribeOn(...)
```

дает чуть больше понимания, что на каком потоке работает, чем 


```
Single.fromCallable { ... }
    .subscribeOn(...)
    .map( ... )

```

Хотя и то, и другое правильно.

2018-11-03 07:46 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/data/DataUtils.java
> +        try {
Эту штуку - в смысле этот блок try =)

2018-11-03 07:49 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +                subscribe(this::updateItems);
А еще - я не увидел установки глобального Error handler-а --> его надо установить 1 раз за все приложение, например, в Application классе.

2018-11-03 07:49 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +                subscribe(this::updateItems);
Читать - вот тут -- https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

2018-11-04 09:20 UTC, AlexeyYakimov commented on app/src/main/java/ru/polosatuk/mycard/NewsDetailsActivity.java
> +        final NewsDisplayableModel news = (NewsDisplayableModel) getIntent().getSerializableExtra(NEWS_KEY_EXTRA);
Знаю и поправлю в 6й домашке:))

2018-11-04 09:21 UTC, AlexeyYakimov commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        progressBar.setVisibility(ProgressBar.INVISIBLE);
Потому что у меня лапки:( сейчас поправлю на GONE

2018-11-04 09:22 UTC, AlexeyYakimov commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        if (disposable != null && !disposable.isDisposed()) {
Паша, это же в 6й домашке будет:) Может до нее оставить эту тему?

2018-11-04 09:25 UTC, AlexeyYakimov commented on app/src/main/java/ru/polosatuk/mycard/newsList/data/DataUtils.java
> +        try {
Ок, но я его выпилю в 5й домашке:)

2018-11-04 09:41 UTC, PoLoSkA commented on app/src/main/java/ru/polosatuk/mycard/NewsDetailsActivity.java
> +        final NewsDisplayableModel news = (NewsDisplayableModel) getIntent().getSerializableExtra(NEWS_KEY_EXTRA);
Ошибочка, поправлю в этой

2018-11-11 17:07 UTC, PStrelchenko requested changes

2018-11-11 17:07 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsView.java
> +    void showNewsDetail(Context context, NewsDisplayableModel item);
В presenter-е, по-хорошему, не должно быть `Context`. Тебе он там и не нужен для открытия новой Activity.
Ты просто делаешь
```
viewState.showNewsDetails(item)
```
И View сама предоставит контекст

2018-11-11 17:07 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/DataUtils.java
> +                Utils.createDate(2018, localDate.get(Calendar.MONTH), localDate.get(Calendar.DAY_OF_MONTH), localDate.get(Calendar.HOUR_OF_DAY) - 5, 34),
Лучше раздербань `Utils` на несколько классов. А то у тебя там и создание даты, и какие-то утилиты для View.

2018-11-11 17:07 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewActivity.java
> +        Log.d(NewsViewActivity.class.getSimpleName(), th.getMessage(), th);
В качестве тэга лучше всегда юзать статическую константу -- потому что после proguard-а твое название класса превратится в тыкву, и ты не поймешь, где у тебя вообще была ошибка.

2018-11-11 17:07 UTC, PStrelchenkoHH commented on app/src/main/java/ru/polosatuk/mycard/newsList/NewsViewPresenter.java
> +        getViewState().showProgressBar(false);
Наверное, не туда добавил эту строчку.
У тебя получается так -- ты показал прогресс. Запустил запрос (он пусть работает 10 секунд). И сразу же убрал прогресс - показываешь пустой список. 
Это не гут

2018-11-11 17:43 UTC, PStrelchenko approved these changes
Гут, поехали к следующей задаче.

2018-11-11 17:49 UTC, merged